name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20  # or whichever version you prefer

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npx tsc --noEmit  # Runs tsc to check for type errors without emitting files

    - name: Run tests
      run: npm run test
